import { useState, type FormEvent } from 'react'
import { BookOpen, FileSearch, FileText, MessageSquareText, Search, Sparkles } from 'lucide-react'
import { api, type AskResponse, type RetrievalResult } from '../api'
import { Alert, Metadata, PageIntro, Panel, SubmitButton } from '../components/Interface'

const suggestions = ['What was Apple total net sales in 2024?', 'What factors affected Services net sales?', 'How does Apple describe its business risks?']
export function ResearchPage() {
  const [query, setQuery] = useState(''); const [mode, setMode] = useState<'ask' | 'retrieve'>('ask'); const [topK, setTopK] = useState(5)
  const [answer, setAnswer] = useState<AskResponse | null>(null); const [chunks, setChunks] = useState<RetrievalResult[] | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); setAnswer(null); setChunks(null); setLoading(true); try { if (mode === 'ask') setAnswer(await api.ask(query, topK)); else setChunks((await api.retrieve(query, topK)).results) } catch (cause) { setError((cause as Error).message) } finally { setLoading(false) } }
  function chooseMode(next: 'ask' | 'retrieve') { setMode(next); setAnswer(null); setChunks(null); setError('') }
  return <><PageIntro label="APPLE 2024 ANNUAL REPORT · GROUNDED RESEARCH" title="Ask the report. Follow the source." text="Search indexed report passages or ask a question answered from retrieved context, with source references alongside the response." icon={BookOpen}/>
    <div className="research-workspace"><Panel className="research-composer"><div className="research-compose-top"><span className="research-icon"><FileSearch size={19}/></span><div><div className="eyebrow">FINANCIAL RESEARCH COPILOT</div><h2>What would you like to know?</h2></div><span className="corpus-badge"><i/>ANNUAL REPORT</span></div>
      <div className="mode-tabs" role="tablist" aria-label="Research mode"><button role="tab" aria-selected={mode === 'ask'} className={mode === 'ask' ? 'selected' : ''} type="button" onClick={() => chooseMode('ask')}><MessageSquareText size={15}/>Ask FinSight</button><button role="tab" aria-selected={mode === 'retrieve'} className={mode === 'retrieve' ? 'selected' : ''} type="button" onClick={() => chooseMode('retrieve')}><Search size={15}/>Retrieve sources</button></div>
      <form onSubmit={submit}><label className="field"><span className="sr-only">{mode === 'ask' ? 'Ask FinSight a question' : 'Search the annual report'}</span><textarea className="research-input" value={query} onChange={event => setQuery(event.target.value)} rows={3} placeholder={mode === 'ask' ? 'Ask a question about Apple’s annual report…' : 'Search for a topic or phrase in the report…'} required/></label><div className="research-compose-bottom"><label className="field topk-field"><span>Context passages</span><select value={topK} onChange={event => setTopK(Number(event.target.value))}>{[3, 5, 7, 10].map(number => <option key={number} value={number}>{number} passages</option>)}</select></label><SubmitButton loading={loading}>{mode === 'ask' ? 'Ask FinSight' : 'Search report'}</SubmitButton></div></form>
      {error && <div className="research-error"><Alert error={error}/><p>Try again, or use Retrieve sources to inspect matching passages directly.</p></div>}
      {!answer && chunks === null && !error && !loading && <div className="suggestion-area"><span className="eyebrow">SUGGESTED QUESTIONS</span><div className="suggestion-list">{suggestions.map(item => <button type="button" key={item} className="suggestion-chip" onClick={() => setQuery(item)}>{item}<span>↗</span></button>)}</div></div>}
      {loading && <div className="research-loading" role="status"><span className="loading-spark"><Sparkles size={17}/></span><span><strong>{mode === 'ask' ? 'Reading the source material…' : 'Searching the indexed report…'}</strong><small>{mode === 'ask' ? 'Gemini is preparing a grounded response.' : 'Retrieving relevant passages.'}</small></span><div className="loading-dots"><i/><i/><i/></div></div>}
      <div className="corpus-note"><FileText size={14}/><span>Source corpus: Apple Inc. 2024 annual report · retrieved passages are source material, not instructions.</span></div>
    </Panel>
    {answer && <section className="research-results" aria-live="polite"><div className="answer-card"><div className="answer-card-head"><span className="answer-spark"><Sparkles size={16}/></span><div><div className="eyebrow">FINSIGHT RESPONSE</div><span>Generated answer</span></div><span className="generated-tag">GROUNDED</span></div><div className="answer-text">{answer.answer}</div><p className="grounding-note">Generated using retrieved annual-report context. Review the cited source references below.</p></div><div className="sources-section"><div className="sources-heading"><div><div className="eyebrow">RETRIEVED EVIDENCE</div><h2>Sources <span>{answer.sources.length}</span></h2></div><span className="sources-label">FROM THE INDEX</span></div>{answer.sources.length ? <div className="source-grid">{answer.sources.map((source, index) => <article className="source-card" key={source.chunk_id}><div className="source-card-top"><span className="source-count">SOURCE {String(index + 1).padStart(2, '0')}</span><span className="source-id">{source.chunk_id}</span></div><div className="source-meta"><Metadata data={source.metadata}/></div></article>)}</div> : <div className="empty-inline">No source references were returned for this answer.</div>}</div></section>}
    {chunks !== null && <Panel className="retrieval-results"><div className="sources-heading"><div><div className="eyebrow">RETRIEVAL RESULTS</div><h2>Matching passages <span>{chunks.length}</span></h2></div><span className="sources-label">RANKED BY MATCH</span></div>{chunks.length ? <div className="chunk-list">{chunks.map((chunk, index) => <article className="chunk-card" key={chunk.chunk_id}><div className="chunk-card-top"><span className="source-count">PASSAGE {String(index + 1).padStart(2, '0')}</span><span className="match-score">Match score {chunk.score.toFixed(3)}</span></div><p>{chunk.text}</p><div className="source-meta"><span className="metadata-item"><b>Chunk</b>{chunk.chunk_id}</span><Metadata data={chunk.metadata}/></div></article>)}</div> : <div className="empty-inline">No matching passages were returned. Try a different query.</div>}</Panel>}
    {!answer && chunks === null && !error && <div className="research-empty-note"><span><BookOpen size={17}/></span><div><strong>Answer and evidence stay distinct.</strong><p>Ask returns a generated response with references. Retrieve sources returns matching passages without generation.</p></div></div>}
    <div className="small-note">Answers are grounded in retrieved passages. The service is expected to report when available context is insufficient.</div>
    </div>
  </>
}
