import { useState, type FormEvent } from 'react'
import { BrainCircuit, MessageSquareText, Sparkles } from 'lucide-react'
import { api, type SentimentResult } from '../api'
import { Alert, PageIntro, Panel, SubmitButton } from '../components/Interface'

export function SentimentPage() {
  const [text, setText] = useState(''); const [result, setResult] = useState<SentimentResult | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); setResult(null); setLoading(true); try { setResult(await api.sentiment(text)) } catch (cause) { setError((cause as Error).message) } finally { setLoading(false) } }
  return <><PageIntro label="FINE-TUNED FINBERT CLASSIFIER" title="Hear the tone in financial language." text="Analyze an earnings excerpt, company statement, or market headline with the existing sentiment service." icon={BrainCircuit}/>
    <div className="sentiment-layout"><Panel className="sentiment-input-panel"><div className="input-panel-kicker"><span className="input-icon"><MessageSquareText size={17}/></span><div><div className="eyebrow">TEXT ANALYSIS</div><h2>Bring the language.</h2></div></div><p className="helper">A financial sentence or short passage is enough to get started.</p><form onSubmit={submit}><label className="field"><span>Text to classify</span><textarea value={text} onChange={event => setText(event.target.value)} rows={8} maxLength={10000} placeholder="Paste a company statement, earnings excerpt, or financial headline…" required/></label><div className="textarea-foot"><span>Sent to the configured FinBERT API</span><span>{text.length.toLocaleString()}/10,000</span></div>{error && <Alert error={error}/>}<div className="form-actions"><SubmitButton loading={loading}>Analyze sentiment</SubmitButton></div></form></Panel>
      {result ? <Panel className={`sentiment-result result-${result.sentiment.toLowerCase()}`}><div className="sentiment-result-top"><div className="eyebrow"><Sparkles size={12}/> CLASSIFICATION RESULT</div><span className="confidence-pill">{(result.confidence * 100).toFixed(1)}% confidence</span></div><div className="sentiment-main"><span className={`sentiment-orb ${result.sentiment.toLowerCase()}`}><BrainCircuit size={28}/></span><div><span className="metric-label">OVERALL SENTIMENT</span><h2 className={`sentiment-word ${result.sentiment.toLowerCase()}`}>{result.sentiment}</h2></div></div><div className="sentiment-rule"/><div className="probability-heading"><h3>Probability breakdown</h3><span>MODEL OUTPUT</span></div>{(['positive', 'neutral', 'negative'] as const).map(label => <div className="prob-row" key={label}><div className="prob-label"><span className={`prob-dot ${label}`}/><span>{label}</span><strong>{(result.probabilities[label] * 100).toFixed(1)}%</strong></div><div className="prob-track"><span className={`prob-fill ${label}`} style={{ width: `${Math.max(0, Math.min(100, result.probabilities[label] * 100))}%` }}/></div></div>)}<p className="result-disclaimer">A language classification estimate, not a recommendation about a security.</p></Panel> : <div className={`sentiment-placeholder ${loading ? 'is-loading' : ''}`} aria-live="polite"><div className="placeholder-art"><span className="placeholder-ring ring-a"/><span className="placeholder-ring ring-b"/><span className="placeholder-center">{loading ? <span className="loading-pulse"><Sparkles size={23}/></span> : <BrainCircuit size={24}/>}</span></div><span className="eyebrow">{loading ? 'READING THE SIGNAL' : 'MODEL RESULT'}</span><h2>{loading ? 'Finding the tone…' : 'Your result will appear here.'}</h2><p>{loading ? 'FinBERT is analyzing the financial language.' : 'Submit text for its sentiment label, confidence, and class probabilities.'}</p>{loading && <div className="loading-track"><span/></div>}</div>}
    </div><div className="small-note">Submitted text is sent to the configured sentiment API. The classifier’s output is not investment advice.</div>
  </>
}
