import { useEffect, useState, type FormEvent, type ReactNode } from 'react'
import { NavLink, Route, Routes, useLocation } from 'react-router-dom'
import { Activity, ArrowRight, BarChart3, BookOpen, BrainCircuit, CircleAlert, FileText, Gauge, Landmark, LoaderCircle, MessageSquareText, Search, ShieldCheck, Sparkles, TrendingUp, Wifi, WifiOff } from 'lucide-react'
import metadata from '../../ml/risk_prediction/model_metadata.json'
import { api, type AskResponse, type Health, type RetrievalResult, type RiskResult, type SentimentResult, type StockResult } from './api'

const nav = [
  { to: '/', label: 'Overview', icon: Gauge }, { to: '/risk', label: 'Risk analysis', icon: ShieldCheck },
  { to: '/stock', label: 'Stock intelligence', icon: TrendingUp }, { to: '/sentiment', label: 'Sentiment', icon: MessageSquareText },
  { to: '/research', label: 'Financial Q&A', icon: BookOpen },
]
const titles: Record<string, [string, string]> = {
  '/': ['Good decisions start with a clearer picture.', 'FINANCIAL INTELLIGENCE'], '/risk': ['Understand the factors behind risk.', 'BANKRUPTCY RISK'],
  '/stock': ['A model view of the next trading day.', 'STOCK INTELLIGENCE'], '/sentiment': ['Read the tone of financial language.', 'FINANCIAL SENTIMENT'], '/research': ['Ask the annual report directly.', 'DOCUMENT RESEARCH'],
}
function Shell({ children }: { children: ReactNode }) {
  const location = useLocation(); const [health, setHealth] = useState<Health | null>(null); const [healthError, setHealthError] = useState(false)
  useEffect(() => { let active = true; const check = () => api.health().then((h) => { if (active) { setHealth(h); setHealthError(false) } }).catch(() => { if (active) { setHealth(null); setHealthError(true) } }); check(); const timer = window.setInterval(check, 30000); return () => { active = false; window.clearInterval(timer) } }, [])
  const title = titles[location.pathname] || titles['/']
  return <div className="app-shell"><aside className="sidebar"><NavLink to="/" className="brand"><span className="brand-mark"><Activity size={19}/></span><span>finsight<span className="brand-ai">.ai</span><small>FINANCIAL INTELLIGENCE</small></span></NavLink><div className="nav-label">WORKSPACE</div><nav>{nav.map(({to,label,icon:Icon}) => <NavLink key={to} to={to} end={to === '/'} className={({isActive}) => `nav-item ${isActive ? 'active' : ''}`}><Icon size={17}/><span>{label}</span>{to === location.pathname && <span className="nav-current"/>}</NavLink>)}</nav><div className="sidebar-foot"><div className="backend-badge"><span className={`status-dot ${health ? 'online' : ''}`}/><span>{health ? 'API connected' : healthError ? 'API unreachable' : 'Checking API'}</span></div><small>Models inform. People decide.</small></div></aside><main className="main"><header className="topbar"><div><div className="eyebrow">{title[1]}</div><div className="page-title">{title[0]}</div></div><div className={`connection ${health ? 'connected' : ''}`}>{health ? <Wifi size={15}/> : <WifiOff size={15}/>}<span>{health ? health.service : 'Backend status'}</span></div></header><div className="content">{children}</div><footer>FinSight AI <span>·</span> Research and analysis tools <span>·</span> Not financial advice</footer></main></div>
}
function PageIntro({ label, title, text, icon: Icon }: {label:string; title:string; text:string; icon: typeof Activity}) { return <div className="page-intro"><div className="intro-icon"><Icon size={20}/></div><div><div className="eyebrow">{label}</div><h1>{title}</h1><p>{text}</p></div></div> }
function Panel({ children, className = '' }: {children:ReactNode; className?:string}) { return <section className={`panel ${className}`}>{children}</section> }
function SubmitButton({loading, children}: {loading:boolean; children:string}) { return <button className="button-primary" disabled={loading}>{loading ? <><LoaderCircle className="spin" size={16}/> Working…</> : <>{children}<ArrowRight size={16}/></>}</button> }
function Alert({error}: {error:string}) { return <div className="alert-error"><CircleAlert size={17}/><span>{error}</span></div> }
function Dashboard() {
 const [health,setHealth]=useState<Health|null>(null); const [error,setError]=useState('')
 useEffect(()=>{api.health().then(setHealth).catch((e:Error)=>setError(e.message))},[])
 const items=[{to:'/risk',name:'Risk analysis',desc:'Bankruptcy probability with SHAP feature attribution.',tag:'XGBoost · SHAP',icon:ShieldCheck,n:'01'},{to:'/stock',name:'Stock intelligence',desc:'A next-day return estimate from a return-target LSTM.',tag:'AAPL · LSTM',icon:TrendingUp,n:'02'},{to:'/sentiment',name:'Financial sentiment',desc:'Classify financial text with fine-tuned FinBERT.',tag:'FinBERT',icon:BrainCircuit,n:'03'},{to:'/research',name:'Financial Q&A',desc:'Search and ask questions grounded in Apple’s 2024 annual report.',tag:'RAG · Annual report',icon:BookOpen,n:'04'}]
 return <><div className="hero"><div className="hero-copy"><div className="hero-kicker"><Sparkles size={14}/> RESEARCH WORKSPACE <span>·</span> MODEL-POWERED</div><h1>See the signal.<br/><em>Understand the context.</em></h1><p>Explore company risk, market signals, financial language, and reported results in one focused workspace.</p><div className="hero-status"><span className={`status-dot ${health?'online':''}`}/>{health ? `${health.service} is ready` : error ? 'Backend could not be reached' : 'Connecting to backend'}{error && <span className="hero-error"> · {error}</span>}</div></div><div className="hero-art"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="art-center"><Landmark size={33}/></div><span className="art-node node-a"><BarChart3 size={17}/></span><span className="art-node node-b"><Search size={17}/></span><span className="art-node node-c"><Activity size={17}/></span><div className="art-caption">DATA <span>→</span> INSIGHT</div></div></div><div className="section-heading"><div><div className="eyebrow">YOUR TOOLKIT</div><h2>Four ways to explore the numbers.</h2></div><span className="section-count">01 — 04</span></div><div className="capability-grid">{items.map(({to,name,desc,tag,icon:Icon,n})=><NavLink to={to} key={to} className="capability"><div className="cap-top"><span className="cap-icon"><Icon size={20}/></span><span className="cap-number">{n}</span></div><h3>{name}</h3><p>{desc}</p><div className="cap-foot"><span>{tag}</span><ArrowRight size={16}/></div></NavLink>)}</div><div className="notice"><FileText size={17}/><span>Model outputs are experimental research signals. They are not investment recommendations or financial advice.</span></div></>
}

const features = (metadata as {features:string[]}).features
const groups: [string, RegExp][] = [['Profitability & margins',/ROA|Margin|Profit Rate|Interest Rate|Net profit|Profit Growth|Net Profit|EPS|Income|Sales Gross|expense|DFL|Interest Coverage/i],['Liquidity & working capital',/Current|Quick|Cash|Working Capital|Inventory|Receivable|Collection|Turnover/i],['Debt & capital structure',/Debt|Liability|Equity|Borrow|fund suitability|Contingent|Net worth|Assets/i],['Growth & operations',/Growth|Revenue|Operating|Asset Turnover|Person|Allocation|GNP|Reinvestment|Per Share|CFO|Funds to/i]]
function RiskPage(){ const [values,setValues]=useState<Record<string,string>>({}); const [result,setResult]=useState<RiskResult|null>(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(false)
 const groupFeatures=groups.map(([label,pattern])=>({label,items:features.filter(f=>pattern.test(f)&& !groups.slice(0,groups.findIndex(g=>g[0]===label)).some(([,prior])=>prior.test(f)))})); const assigned=new Set(groupFeatures.flatMap(g=>g.items)); groupFeatures.push({label:'Other model features',items:features.filter(f=>!assigned.has(f))})
 async function submit(e:FormEvent){e.preventDefault();setError('');setResult(null);const missing=features.filter(f=>values[f]===undefined||values[f].trim()==='');if(missing.length){setError(`Enter a numeric value for all 94 model inputs. ${missing.length} remaining.`);return}const parsed:Record<string,number>={};for(const f of features){const n=Number(values[f]);if(!Number.isFinite(n)){setError(`“${f}” must be a finite number.`);return}parsed[f]=n}setLoading(true);try{setResult(await api.risk(parsed))}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 return <><PageIntro label="XGBOOST CLASSIFIER · SHAP EXPLANATIONS" title="Bankruptcy risk profile" text="Provide values for the 94 features expected by the trained model. Feature labels come directly from its metadata." icon={ShieldCheck}/><div className="split-layout"><form onSubmit={submit}><Panel><div className="panel-head"><div><div className="eyebrow">COMPANY INPUTS</div><h2>Financial indicators</h2></div><span className="count-pill">{features.length} FEATURES</span></div><p className="helper">Enter decimal values for ratios and numeric values for counts. Use the source dataset’s feature scale.</p>{groupFeatures.map((g,i)=><details className="feature-group" key={g.label} open={i===0}><summary><span>{g.label}</span><small>{g.items.length} inputs</small></summary><div className="feature-grid">{g.items.map(f=><label className="field" key={f}><span title={f}>{f.trim()}</span><input type="number" step="any" value={values[f]??''} onChange={e=>setValues({...values,[f]:e.target.value})} placeholder="Enter value" required aria-label={f}/></label>)}</div></details>)}{error&&<Alert error={error}/>}<div className="form-actions"><button type="button" className="button-secondary" onClick={()=>{setValues({});setResult(null);setError('')}}>Clear all</button><SubmitButton loading={loading}>Analyze risk</SubmitButton></div></Panel></form><div className="result-column"><Panel className="result-panel"><div className="eyebrow">INFERENCE RESULT</div>{result?<><div className="risk-score"><strong>{(result.bankruptcy_probability*100).toFixed(1)}<small>%</small></strong><span>Bankruptcy probability</span></div><div className={`risk-level ${result.risk_level.toLowerCase()}`}>{result.risk_level} risk</div><div className="meter"><span style={{width:`${Math.max(0,Math.min(100,result.bankruptcy_probability*100))}%`}}/></div><p className="helper">Probability and category returned by the model.</p></>:<div className="empty-result"><span className="empty-icon"><ShieldCheck size={23}/></span><h3>Your result will appear here</h3><p>Complete all 94 inputs and run the analysis to see the model output.</p></div>}</Panel>{result&&<Panel><div className="eyebrow">SHAP EXPLANATION</div><h2 className="panel-title">Top contributors</h2><p className="helper">Contribution direction reflects the model output.</p><div className="contributor-list">{result.top_contributors.map(c=><div className="contributor" key={c.feature}><span title={c.feature}>{c.feature.trim()}</span><strong className={c.shap_value>=0?'positive-shap':'negative-shap'}>{c.shap_value>=0?'+':''}{c.shap_value.toFixed(4)}</strong></div>)}</div></Panel>}<div className="small-note">Predictions are statistical estimates and are not financial advice.</div></div></div></>
}

function StockPage(){const [ticker,setTicker]=useState('AAPL');const [result,setResult]=useState<StockResult|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(false);async function submit(e:FormEvent){e.preventDefault();setError('');setResult(null);setLoading(true);try{setResult(await api.stock(ticker.trim().toUpperCase()))}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 return <><PageIntro label="MULTIVARIATE RETURN-TARGET LSTM" title="Stock intelligence" text="Inspect the model’s next-day return estimate and implied close using its existing stock API." icon={TrendingUp}/><div className="narrow-layout"><Panel><div className="eyebrow">FORECAST INPUT</div><h2 className="panel-title">Choose a ticker</h2><form className="inline-form" onSubmit={submit}><label className="field"><span>Stock ticker</span><input value={ticker} onChange={e=>setTicker(e.target.value)} placeholder="AAPL" required/></label><SubmitButton loading={loading}>Run prediction</SubmitButton></form>{error&&<Alert error={error}/>}</Panel>{result?<><Panel><div className="result-topline"><div><div className="eyebrow">MODEL PREDICTION · {result.ticker}</div><h2 className="panel-title large">Next-day estimate</h2></div><span className="count-pill">{result.model_type}</span></div><div className="stock-stats"><div><span>Latest close</span><strong>${result.latest_close.toFixed(2)}</strong></div><div><span>Predicted next-day return</span><strong className={result.predicted_next_day_return>=0?'positive-shap':'negative-shap'}>{result.predicted_next_day_return>=0?'+':''}{(result.predicted_next_day_return*100).toFixed(3)}%</strong></div><div><span>Predicted next close</span><strong>${result.predicted_next_close.toFixed(2)}</strong></div><div><span>Sequence length</span><strong>{result.sequence_length} <small>trading days</small></strong></div></div></Panel><div className="notice warning"><CircleAlert size={17}/><span>This is a model prediction, not a market quote. On the evaluated test period, the return-target LSTM did not outperform the persistence baseline. Past evaluation does not predict future performance.</span></div></>:<div className="empty-page"><TrendingUp size={22}/><h3>Prediction results appear here</h3><p>The trained model currently supports AAPL. The API will return an error for unsupported tickers or missing model artifacts.</p></div>}<div className="small-note">For research and educational use only. Not investment advice.</div></div></>
}

function SentimentPage(){const [text,setText]=useState('');const [result,setResult]=useState<SentimentResult|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(false);async function submit(e:FormEvent){e.preventDefault();setError('');setResult(null);setLoading(true);try{setResult(await api.sentiment(text))}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 return <><PageIntro label="FINE-TUNED FINBERT CLASSIFIER" title="Financial sentiment" text="Classify a financial statement, earnings excerpt, or market headline using the trained sentiment service." icon={BrainCircuit}/><div className="narrow-layout"><Panel><div className="eyebrow">TEXT ANALYSIS</div><h2 className="panel-title">Paste financial text</h2><form onSubmit={submit}><label className="field"><span>Text to classify</span><textarea value={text} onChange={e=>setText(e.target.value)} rows={7} maxLength={10000} placeholder="Paste a company statement, earnings excerpt, or financial headline…" required/></label><div className="textarea-foot"><span>Submitted text is sent to the configured FinBERT API.</span><span>{text.length}/10,000</span></div><div className="form-actions"><SubmitButton loading={loading}>Analyze sentiment</SubmitButton></div></form>{error&&<Alert error={error}/>}</Panel>{result?<Panel><div className="eyebrow">CLASSIFICATION RESULT</div><div className="sentiment-head"><span className={`sentiment-tag ${result.sentiment}`}>{result.sentiment}</span><span>Confidence <strong>{(result.confidence*100).toFixed(1)}%</strong></span></div><h2 className="panel-title">Class probabilities</h2>{(['positive','neutral','negative'] as const).map(label=><div className="prob-row" key={label}><div><span>{label}</span><strong>{(result.probabilities[label]*100).toFixed(1)}%</strong></div><div className="prob-track"><span className={`prob-fill ${label}`} style={{width:`${result.probabilities[label]*100}%`}}/></div></div>)}</Panel>:<div className="small-note">The classifier’s output is a language-model estimate, not a recommendation about a security.</div>}</div></>
}

function FinancialQA(){const [query,setQuery]=useState('');const [mode,setMode]=useState<'ask'|'retrieve'>('ask');const [topK,setTopK]=useState(5);const [answer,setAnswer]=useState<AskResponse|null>(null);const [chunks,setChunks]=useState<RetrievalResult[]|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(false);async function submit(e:FormEvent){e.preventDefault();setError('');setAnswer(null);setChunks(null);setLoading(true);try{if(mode==='ask')setAnswer(await api.ask(query,topK));else setChunks((await api.retrieve(query,topK)).results)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 return <><PageIntro label="APPLE 2024 ANNUAL REPORT · RETRIEVAL AUGMENTED" title="Financial Q&A" text="Search the indexed annual report or ask for an answer grounded in its retrieved passages." icon={BookOpen}/><div className="narrow-layout"><Panel><div className="mode-tabs"><button className={mode==='ask'?'selected':''} type="button" onClick={()=>{setMode('ask');setAnswer(null);setChunks(null);setError('')}}><MessageSquareText size={16}/> Ask</button><button className={mode==='retrieve'?'selected':''} type="button" onClick={()=>{setMode('retrieve');setAnswer(null);setChunks(null);setError('')}}><Search size={16}/> Retrieve only</button></div><form onSubmit={submit}><label className="field"><span>{mode==='ask'?'Your question':'Search the report'}</span><textarea value={query} onChange={e=>setQuery(e.target.value)} rows={3} placeholder="e.g. What factors affected Services net sales?" required/></label><div className="qa-controls"><label className="field"><span>Source passages</span><select value={topK} onChange={e=>setTopK(Number(e.target.value))}>{[3,5,7,10].map(n=><option key={n} value={n}>{n} passages</option>)}</select></label><SubmitButton loading={loading}>{mode==='ask'?'Ask report':'Retrieve passages'}</SubmitButton></div></form>{error&&<Alert error={error}/>}<div className="corpus-note"><FileText size={15}/> Search scope: Apple Inc. 2024 annual report indexed in the configured corpus.</div></Panel>{answer&&<Panel><div className="eyebrow">GROUNDED ANSWER</div><div className="answer-text">{answer.answer}</div><div className="source-heading">SOURCE REFERENCES <span>{answer.sources.length}</span></div>{answer.sources.length?answer.sources.map(s=><div className="source-row" key={s.chunk_id}><span className="source-id">{s.chunk_id}</span><span>{Object.entries(s.metadata).filter(([,v])=>v!=null).map(([k,v])=>`${k.replace('_',' ')}: ${String(v)}`).join(' · ')||'Annual report'}</span></div>):<div className="empty-inline">No source passages were returned for this answer.</div>}<p className="grounding-note">Generated from retrieved annual-report context. If the available context is insufficient, the service is expected to say so.</p></Panel>}{chunks!==null&&<Panel><div className="eyebrow">RETRIEVED PASSAGES</div><h2 className="panel-title">{chunks.length} matches</h2>{chunks.length?chunks.map(c=><article className="chunk" key={c.chunk_id}><div className="chunk-top"><span className="source-id">{c.chunk_id}</span><span>Match score {c.score.toFixed(3)}</span></div><p>{c.text}</p><div className="chunk-meta">{Object.entries(c.metadata).filter(([,v])=>v!=null).map(([k,v])=>`${k.replace('_',' ')}: ${String(v)}`).join(' · ')}</div></article>):<div className="empty-inline">No matching passages were returned. Try another query.</div>}</Panel>}<div className="small-note">Answers are grounded only in retrieved report passages. Retrieved documents are treated as source material, not instructions.</div></div></>
}
export default function App(){return <Shell><Routes><Route path="/" element={<Dashboard/>}/><Route path="/risk" element={<RiskPage/>}/><Route path="/stock" element={<StockPage/>}/><Route path="/sentiment" element={<SentimentPage/>}/><Route path="/research" element={<FinancialQA/>}/><Route path="*" element={<Dashboard/>}/></Routes></Shell>}
